_wandb:
    value:
        cli_version: 0.22.3
        e:
            v5leido0ij33kcj33xjm2lal9k6tw1vh:
                codePath: Breath_dataset_and_apps/code/brp-ml-model-main/models/Pytorch/show.py
                codePathLocal: show.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "982240026624"
                        used: "97120313344"
                email: s203668@student.pg.edu.pl
                executable: /usr/bin/python
                git:
                    commit: 9f3bd8c5897d7d8f355bbe22cfc44f4b8906dcf3
                    remote: https://github.com/Breath-Classification/Breath-Project.git
                host: 817d7e527c50
                memory:
                    total: "32809422848"
                os: Linux-6.14.0-36-generic-x86_64-with-glibc2.35
                program: /workspaces/Breath-Project/Breath_dataset_and_apps/code/brp-ml-model-main/models/Pytorch/show.py
                python: CPython 3.11.14
                root: /workspaces/Breath-Project/Breath_dataset_and_apps/code/brp-ml-model-main/models/Pytorch
                startedAt: "2025-12-04T11:27:15.640489Z"
                writerId: v5leido0ij33kcj33xjm2lal9k6tw1vh
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 2
                - 3
                - 41
            "2":
                - 1
                - 2
                - 3
                - 41
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.11.14
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
batch_size:
    value: 32
block_size:
    value:
        - 12
epochs:
    value: 3
loss_fn:
    value: CrossEntropyLoss
lr:
    value: 0.001
model:
    value: GRU
optimizer:
    value: Adam
sensor:
    value: tens
